/* Generated by re2c 0.13.5 on Fri Sep  4 10:55:27 2009 */
#line 3 "Zend/zend_language_scanner_defs.h"

enum YYCONDTYPE {
	yycST_IN_SCRIPTING,
	yycST_IN_SGML_ATTR_EXPR,
	yycST_LOOKING_FOR_PROPERTY,
	yycST_BACKQUOTE,
	yycST_DOUBLE_QUOTES,
	yycST_HEREDOC,
	yycST_LOOKING_FOR_VARNAME,
	yycST_VAR_OFFSET,
	yycINITIAL,
	yycST_IN_SGML_TAG,
	yycST_END_HEREDOC,
	yycST_NOWDOC,
};
